### ISSUE TITLE
Unable to access the button at the bottom

### ISSUE THREAD

**Issue by stinglama** [VishnuSanal/Quotes#71]
**Describe the bug**
I'm using lineageOS 18.1 on my Poco F3/ Mi 11x. I'm unable to access the button at the bottom. I'm facing this issue only on this mobile, I have another mobile on which there is no such issue. Please ignore the clarity of the video.

https://user-images.githubusercontent.com/89147103/143814080-e038b594-e622-42a8-b141-4d650a51c0ed.mp4

**Comment by VishnuSanal** [comment]
@stinglama Hello! Thanks for reporting, will look into this as soon as possible. :)

**Comment by VishnuSanal** [comment]
@stinglama Oops! This is indeed a bug. :(

Do you mind providing me with the following details? Thanks!

- Did you start to face this issue from v2.7.0 or you had this issue in the previous versions too?
- Confirm your screen size is 6.67” and 2400x1080
- Also the screen size & resolution for the other phone in which it worked fine.

Also, feel free to join [t.me/QuotesStatusCreator](t.me/QuotesStatusCreator) so that we can discuss more about this specific issue & the app in general.

Thanks for reporting this issue & offering your valuable help in improving our app. :)

**Comment by stinglama** [comment]
@VishnuSanal 

- I have tried the following versions - 2.6.1, 2.6.2, 2.7.0 . Facing the same issue in all the tested/specified versions.
- Yes the screen size is 6.67" and 1080 x 2400 . But I found an issue here. I tried 2 apps (CPU-Z (Play Store) and SysInfo(FDroid). Both of them show my screen size as 66.6", lol that's interesting. Attaching screenshots for the same.
![SysInfo](https://user-images.githubusercontent.com/89147103/143996701-20607633-25ff-4bcd-beec-c08f2b250ffc.png)
![CPU-Z](https://user-images.githubusercontent.com/89147103/143996723-7102945c-1621-40fc-bdf6-1dec7caa4519.png)

- I second mobile on which I tested is Redmi Note 7 Pro. The screen size is 6.3" and 1080 x 2340 (Shown correctly in the CPU-Z and SysInfo).

**Comment by shuvashish76** [comment]
https://user-images.githubusercontent.com/48226312/147722318-afa47c5e-963f-4f9c-b414-85ffc83059d3.mp4

Similar issue.

**Device details:**
Android: _8.1.0_
Screen size: Width _1200px_, Height _1920px_ (tested with [CPU info](https://github.com/kamgurgul/cpu-info))

**Comment by VishnuSanal** [comment]
@stinglama this issue must be fixed with the latest release [v3.0.0](https://github.com/VishnuSanal/Quotes/releases/tag/v3.0.0), please reopen if it is not the case :)
